#
#       @(#)resolv.conf    1.0 (2.11BSD) 2026/1/12
#
# Settings in this file must match /etc/netstart and /etc/hosts
#
# Specify your domain on the following line
domain example.com
# Specify your name servers (DNS lookup) on the following line(s)
# The examples given are public-access nameservers from Cloudflare and Google
nameserver 1.1.1.1
nameserver 8.8.4.4
nameserver 8.8.8.8
